export const albums = [
  {
    artist: "Kanonenfieber",
    album: "Die Urkatastrophe",
    rank: "1",
    myRate: "100",
    criticsRate: "90",
    dateRelease: "2024-September-20",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/984930-die-urkatastrophe_122510.jpg",
    spotifyLink: "https://open.spotify.com/album/15cBVOLGxioRUCDrkcLiAr",
    genres: ["Black Metal", "Melodic Black Metal", "Blackened Death Metal"],
  },
  {
    artist: "Gaerea",
    album: "Coma",
    rank: "2",
    myRate: "99",
    criticsRate: "83",
    dateRelease: "2024-October-25",
    cover: "https://cdn2.albumoftheyear.org/375x/album/1019321-coma_091656.jpg",
    spotifyLink: "https://open.spotify.com/album/4i9i7I98VBon2pJOWBtbX1",
    genres: [
      "Black Metal",
      "Atmospheric Black Metal",
      "Melodic Death Metal",
      "Post Black Metal",
    ],
  },
  {
    artist: "Disembodied Tyrant & Synestia",
    album: "The Poetic Edda",
    rank: "3",
    myRate: "98",
    criticsRate: "NR",
    dateRelease: "2024-May-03",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/688127-the-poetic-edda_0046.jpg",
    spotifyLink: "https://open.spotify.com/album/3AO82S43rn68Vk4FLgNXKp",
    genres: ["Deathcore", "Symphonic Deathcore", "Neoclassical Metal"],
    type: "ep",
    epRank: "1",
  },
  {
    artist: "Fit for an Autopsy",
    album: "The Nothing That Is",
    rank: "4",
    myRate: "97",
    criticsRate: "77",
    dateRelease: "2024-October-25",
    description: "",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1025833-the-nothing-that-is_141102.jpg",
    spotifyLink: "https://open.spotify.com/album/4ZYfWm41dWgewV1yMV4zmU",
    genres: ["Deathcore", "Groove Metal", "Djent"],
  },
  {
    artist: "Iotunn",
    album: "Kinship",
    rank: "5",
    myRate: "96",
    criticsRate: "88",
    dateRelease: "2024-October-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1062107-kinship_125657.jpg",
    spotifyLink: "https://open.spotify.com/album/2XS9Fdf7FWNhWp4zlveMHC",
    genres: ["Progressive Metal", "Melodic Death Metal"],
  },
  {
    artist: "Akhlys",
    album: "House of the Black Geminus",
    rank: "6",
    myRate: "96",
    criticsRate: "NR",
    dateRelease: "2024-july-5",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/922140-house-of-the-black-geminus_153204.jpg",
    spotifyLink: "https://open.spotify.com/album/2hzBIujiK4PM4Vs0PpWfju",
    genres: ["Atmospheric Black Metal", "Horrorcore", "Dark Ambient"],
  },
  {
    artist: "Ulcerate",
    album: "Cutting the Throat of God",
    rank: "7",
    myRate: "95",
    criticsRate: "88",
    dateRelease: "2024-june-14",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/901868-cutting-the-throat-of-god_225949.jpg",
    spotifyLink: "https://open.spotify.com/album/2QNcQNDeIvL0EWOSP87iSm",
    genres: [
      "Technical Death Metal",
      "Dissonant Death Metal",
      "Atmospheric Sludge Metal",
    ],
  },
  {
    artist: "wormwood",
    album: "The Star",
    rank: "8",
    myRate: "95",
    criticsRate: "40",
    dateRelease: "2024-May-31",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/876824-the-star_110836.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5LJYblFx6TQQkXpmFnid89?si=o0C-P-XqTYK1_XI_HqdAiw",
    genres: ["Melodic Black Metal", "Atmospheric Black Metal"],
  },
  {
    artist: "Crippling Alcoholism",
    album: "With Love from a Padded Room",
    rank: "9",
    myRate: "94",
    criticsRate: "NR",
    dateRelease: "2024-February-29",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/898296-with-love-from-a-padded-room_043706.jpg",
    spotifyLink: "https://open.spotify.com/album/0RtIISlw4JR8qucHOgaulK",
    genres: ["Gothic Rock", "Post Metal", "Darkwave"],
  },
  {
    artist: "Panzerfaust",
    album: "The Suns of Perdition IV: To Shadow Zion",
    rank: "10",
    myRate: "94",
    criticsRate: "80",
    dateRelease: "2024-November-22",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1079656-the-suns-of-perdition-iv-to-shadow-zion_143121.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4qvtmdzVR2uRie3dVhMZtM?si=hJ2CFxJqRb2wdyH9p-b_Hg",
    genres: ["Black Metal", "Atmospheric Black Metal"],
  },
  {
    artist: "Uboa",
    album: "Impossible Light",
    rank: "11",
    myRate: "93",
    criticsRate: "NR",
    dateRelease: "2024-june-28",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/998246-impossible-light_020319.jpg",
    spotifyLink: "https://open.spotify.com/album/1ZwJMEEaBifkdvQl793ek3",
    genres: [
      "Death Industrial",
      "Dark Ambient",
      "Post Metal",
      "Neoclassical Darkwave",
    ],
  },
  {
    artist: "Oceano",
    album: "Living Chaos",
    rank: "12",
    myRate: "93",
    criticsRate: "77",
    dateRelease: "2024-august-30",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/978419-living-chaos_161151.jpg",
    spotifyLink: "https://open.spotify.com/album/3exzrDKmQgQVJFtbiiBZi6",
    genres: ["Deathcore"],
  },
  {
    artist: "Blood Incantation",
    album: "Absolute Elsewhere",
    rank: "13",
    myRate: "92",
    criticsRate: "87",
    dateRelease: "2024-october-4",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/997344-absolute-elsewhere_141614.jpg",
    spotifyLink: "https://open.spotify.com/album/7hriIeLMviZKpNfcXgpsd8",
    genres: ["Progressive Death Metal", "Technical Deaths Metal"],
  },
  {
    artist: "Fleshgod Apocalypse",
    album: "Opera",
    rank: "14",
    myRate: "92",
    criticsRate: "87",
    dateRelease: "2024-August-23",
    cover: "https://cdn2.albumoftheyear.org/375x/album/984612-opera_040704.jpg",
    spotifyLink: "https://open.spotify.com/album/1dDS9EG35qdgeshBzEP2ja",
    genres: ["Technical Deaths Metal", "Symphonic Metal", "Neoclassical Metal"],
  },
  {
    artist: "Worm Shepherd",
    album: "Hunger",
    rank: "15",
    myRate: "92",
    criticsRate: "NR",
    dateRelease: "2024-November-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1077507-hunger_003453.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6ieqQaDcBsbEq569f8wKHl?si=FdA6-r7qR1SE26eItiPZdA",
    genres: ["Deathcore", "Blackened Death Metal", "Symphonic Black Metal"],
  },
  {
    artist: "Psychonaut 4",
    album: "…Of Mourning",
    rank: "16",
    myRate: "92",
    criticsRate: "NR",
    dateRelease: "2024-October-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1051676-of-mourning_020923.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5SCmr0N6XlXf3s7cohLt4k?si=cLwcT3v-QXuiNExeOngwpg",
    genres: ["DSBM", "Black Metal", "Atmospheric Black Metal"],
  },
  {
    artist: "Ihsahn",
    album: "IHSAHN",
    rank: "17",
    myRate: "92",
    criticsRate: "85",
    dateRelease: "2024-February-16",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/797214-ihsahn_130727.jpg",
    spotifyLink: "https://open.spotify.com/album/78eWgdCbll6LBKZR696IBE",
    genres: [
      "Symphonic Metal",
      "Black Metal",
      "Symphonic Black Metal",
      "Progressive Metal",
    ],
  },
  {
    artist: "Immortal Disfigurement",
    album: "KING",
    rank: "18",
    myRate: "92",
    criticsRate: "NR",
    dateRelease: "2024-June-7",
    cover: "https://cdn2.albumoftheyear.org/375x/album/979592-king_181006.jpg",
    spotifyLink:
      "https://open.spotify.com/album/2aHlXLfPMPWlGr248ZeR7E?si=BKPlLW0ZRxW-u3ciH8zQ2Q",
    genres: ["Deathcore", "Symphonic Metal"],
  },
  {
    artist: "Counterparts",
    album: "Heaven Let Them Die",
    rank: "19",
    myRate: "91",
    criticsRate: "84",
    dateRelease: "2024-November-7",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1125106-heaven-let-them-die_151041.jpg",
    spotifyLink: "https://open.spotify.com/album/5pdSJTWNlQj6RJbYPgTFGZ",
    genres: ["Metalcore", "Deathcore"],
    type: "ep",
    epRank: "2",
  },
  {
    artist: "156/Silence",
    album: "People Watching",
    rank: "20",
    myRate: "91",
    criticsRate: "81",
    dateRelease: "2024-september-13",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1013966-people-watching_143538.jpg",
    spotifyLink: "https://open.spotify.com/album/1PRvYCv9h0rlR4AP54yOnN",
    genres: ["Deathcore", "Metalcore", "Post-Hardcore"],
  },
  {
    artist: "Distant",
    album: "Tsukuyomi: The Origin",
    rank: "21",
    myRate: "91",
    criticsRate: "85",
    dateRelease: "2024-november-22",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1067927-tsukuyomi-the-origin_151014.jpg",
    spotifyLink: "https://open.spotify.com/album/0EZiuTBQrIrbItsLBwkjUk",
    genres: ["Deathcore"],
  },
  {
    artist: "Saidan",
    album: "Visual Kill: The Blossoming of Psychotic Depravity",
    rank: "22",
    myRate: "91",
    criticsRate: "92",
    dateRelease: "2024-may-24",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/931268-visual-kill-the-blossoming-of-psychotic-depravity_174453.jpg",
    spotifyLink: "https://open.spotify.com/album/3GRCZH5yCGXRftwsYOhR5y",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Mister Sister Fister & Infant Annihilator",
    album: "Mister Sister Fister: Re Conception",
    rank: "23",
    myRate: "90",
    criticsRate: "NR",
    dateRelease: "2024-october-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1103070-mister-sister-fister-re-conception_200330.jpg",
    spotifyLink:
      "https://open.spotify.com/album/2pdbIE7lO5QMb2dDh0tKRZ?si=Dkssoz3TR8W9eZ4Xy_05NQ",
    genres: ["Deathcore"],
    type: "ep",
    epRank: "3",
  },
  {
    artist: "Mitochondrion",
    album: "Vitriseptome",
    rank: "24",
    myRate: "90",
    criticsRate: "80",
    dateRelease: "2024-november-1",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1100899-vitriseptome_073040.jpg",
    spotifyLink: "https://open.spotify.com/album/1PRvYCv9h0rlR4AP54yOnN",
    genres: ["Blackened Death Metal"],
  },
  {
    artist: "Swallow The Sun",
    album: "Shining",
    rank: "25",
    myRate: "90",
    criticsRate: "76",
    dateRelease: "2024-october-18",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1042431-shining_190541.jpg",
    spotifyLink: "https://open.spotify.com/album/1Bk8bpwSWIXDRCJpzEQyPH",
    genres: ["Doom Metal"],
  },
  {
    artist: "Bonecarver",
    album: "Unholy Dissolution",
    rank: "26",
    myRate: "90",
    criticsRate: "NR",
    dateRelease: "2024-may-31",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/934681-unholy-dissolution_133934.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6mXbBnsjq2mNPO10t9IAPp?si=Gk0DkhDsRECmZBrCOhKWuQ",
    genres: ["Deathcore"],
    type: "ep",
    epRank: "4",
  },
  {
    artist: "Ingested",
    album: "The Tide of Death and Fractured Dreams",
    rank: "27",
    myRate: "89",
    criticsRate: "73",
    dateRelease: "2024-april-5",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/849419-the-tide-of-death-and-fractured-dreams_000218.jpg",
    spotifyLink: "https://open.spotify.com/album/1vrBZpr5a4DEPJNMnpzPkM",
    genres: ["Brutal Death Metal"],
  },
  {
    artist: "Yoth Iria",
    album: "Blazing Inferno",
    rank: "28",
    myRate: "89",
    criticsRate: "80",
    dateRelease: "2024-november-8",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1056019-blazing-inferno_173142.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4GBII1a9TYygGS6FYE5FnJ?si=HnvJzIYbSJW28zRjXBDbtg",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Summoning The Lich",
    album: "Under the Reviled Throne",
    rank: "29",
    myRate: "89",
    criticsRate: "73",
    dateRelease: "2024-july-26",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/958000-under-the-reviled-throne_023156.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5tSuVWooK3ZtbWRBz7pJ0p?si=Eu7wMG7XRHalu6lVwylf7g",
    genres: ["Deathcore"],
  },
  {
    artist: "Chat Pile",
    album: "Cool World",
    rank: "30",
    myRate: "88",
    criticsRate: "83",
    dateRelease: "2024-october-11",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1015369-cool-world_221925.jpg",
    spotifyLink: "https://open.spotify.com/album/3k7GhMNdQ0KXGkC84qVRf2",
    genres: ["Noise Rock"],
  },
  {
    artist: "A Wake In Providence",
    album: "I Write To You, My Darling Decay",
    rank: "31",
    myRate: "88",
    criticsRate: "NR",
    dateRelease: "2024-July-26",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/963105-i-write-to-you-my-darling-decay_030514.jpg",
    spotifyLink:
      "https://open.spotify.com/album/65P5Jm9OqRUUbINjiYmiOu?si=Lo7pQqStQ8Csq3wv3BfPyw",
    genres: ["Deathcore"],
  },
  {
    artist: "Darko",
    album: "Starfire",
    rank: "32",
    myRate: "88",
    criticsRate: "76",
    dateRelease: "2024-june-5",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/957709-starfire_173905.jpg",
    spotifyLink: "https://open.spotify.com/album/3IXsOde67YmhbBbt4Vknv0",
    genres: ["Deathcore"],
  },
  {
    artist: "Nocturnal Depression",
    album: "Perpétuelle Eclipse",
    rank: "33",
    myRate: "88",
    criticsRate: "NR",
    dateRelease: "2024-september-26",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1085837-perpetuelle-eclipse_145429.jpg",
    spotifyLink:
      "https://open.spotify.com/album/1HyIneYUXvJ5jtzPXsYsHf?si=-C4MDjW4SaKXcuY4nYr9Mg",
    genres: ["DSBM"],
  },
  {
    artist: "Entheos",
    album: "An End To Everything",
    rank: "34",
    myRate: "87",
    criticsRate: "77",
    dateRelease: "2024-october-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1013550-an-end-to-everything_055503.jpg",
    spotifyLink: "https://open.spotify.com/album/4v2BDAKl8BuCw8v2wdJRmz",
    genres: ["Progressive Death Metal"],
    type: "ep",
    epRank: "5",
  },
  {
    artist: "Oranssi Pazuzu",
    album: "Muuntautuja",
    rank: "35",
    myRate: "87",
    criticsRate: "78",
    dateRelease: "2024-october-11",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1033199-muuntautuja_034914.jpg",
    spotifyLink: "https://open.spotify.com/album/6cRCD79pIJvu5aeKWVtskd",
    genres: ["Avant-Garde Metal"],
  },
  {
    artist: "Dwarrowdelf",
    album: "The Fallen Leaves",
    rank: "36",
    myRate: "87",
    criticsRate: "90",
    dateRelease: "2024-february-2",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/863081-the-fallen-leaves_074649.jpg",
    spotifyLink:
      "https://open.spotify.com/album/7qx5FvIWedRIWAJkRpq5Hu?si=dyNIh8GoRsGnq_sI7j3Cag",
    genres: ["Atmospheric Black Metal"],
  },
  {
    artist: "Unhallowed Deliverance",
    album: "Of Spectres and Strife",
    rank: "37",
    myRate: "87",
    criticsRate: "NR",
    dateRelease: "2024-May-10",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/957588-of-spectres-and-strife_143757.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6lmkK5tz3YUwQIATsSW9Ml?si=sgxPP_H5SoyNm6eFAi1m-g",
    genres: ["Technical Death Metal"],
  },
  {
    artist: "Allt",
    album: "From The New World",
    rank: "38",
    myRate: "87",
    criticsRate: "82",
    dateRelease: "2024-october-4",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1028066-from-the-new-world_205336.jpg",
    spotifyLink: "https://open.spotify.com/album/2sdKwkwaVrSlhKdTuAf2SC",
    genres: ["Metalcore"],
  },
  {
    artist: "Sylosis",
    album: "The Path",
    rank: "39",
    myRate: "86",
    criticsRate: "NR",
    dateRelease: "2024-October-3",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1091712-the-path_210133.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4iZM0ieSYmfdxaPrKceTu5?si=bKIfH24lQYaqmEjQiirUXw",
    genres: ["Melodic Death Metal"],
    type: "ep",
    epRank: "6",
  },
  {
    artist: "Boundaries",
    album: "Death Is Little More",
    rank: "40",
    myRate: "86",
    criticsRate: "86",
    dateRelease: "2024-March-29",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/864209-death-is-little-more_144231.jpg",
    spotifyLink: "https://open.spotify.com/album/3tyx4wUPmjmHcJHS1jb4eQ",
    genres: ["Metalcore"],
  },
  {
    artist: "Hiraes",
    album: "Dormant",
    rank: "41",
    myRate: "86",
    criticsRate: "60",
    dateRelease: "2024-january-2",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/849793-dormant_120622.jpg",
    spotifyLink:
      "https://open.spotify.com/album/7HYBfqEXZfP4JYfJcrHckC?si=owEV5Le4Q4mKV4prSgAV6Q",
    genres: ["Melodic Death Metal"],
  },
  {
    artist: "Morokh",
    album: "X",
    rank: "42",
    myRate: "86",
    criticsRate: "NR",
    dateRelease: "2024-november-1",
    cover: "https://cdn2.albumoftheyear.org/375x/album/1118815-x_211617.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5ijgDtPKlu1NUDEaADPvzl?si=qYAAoc1FTAWmUR9-OZOwKQ",
    genres: ["Blackened Sludge Metal"],
    type: "ep",
    epRank: "7",
  },
  {
    artist: "Imminence",
    album: "The Black",
    rank: "43",
    myRate: "86",
    criticsRate: "80",
    dateRelease: "2024-April-12",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/884489-the-black_215209.jpg",
    spotifyLink: "https://open.spotify.com/album/7DYQgveBQDY1xyj4XJ3zzY",
    genres: ["Metalcore"],
  },
  {
    artist: "Borknagar",
    album: "Fall",
    rank: "44",
    myRate: "85",
    criticsRate: "84",
    dateRelease: "2024-february-23",
    cover: "https://cdn2.albumoftheyear.org/375x/album/864127-fall_130632.jpg",
    spotifyLink: "https://open.spotify.com/album/5nK2siMASeGKxTsX9GqY3v",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Assemble The Chariots",
    album: "Unyielding Night",
    rank: "45",
    myRate: "85",
    criticsRate: "83",
    dateRelease: "2024-July-19",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/994891-unyielding-night_061930.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6BUxjFkGEkJUIiCKbtpWpW?si=pulEOzeHSYKPbGP-BM8ySw",
    genres: ["Symphonic Deathcore"],
  },
  {
    artist: "Necrophobic",
    album: "In the Twilight Grey",
    rank: "46",
    myRate: "85",
    criticsRate: "84",
    dateRelease: "2024-March-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/885702-in-the-twilight-grey_182524.jpg",
    spotifyLink: "https://open.spotify.com/album/2EtaPsV5q2n21XiyF8UclQ",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "In Vain",
    album: "Solemn",
    rank: "47",
    myRate: "84",
    criticsRate: "85",
    dateRelease: "2024-april-19",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/915476-solemn_143731.jpg",
    spotifyLink: "https://open.spotify.com/album/7Kabp5ZGmmD9rF66vpdJs8",
    genres: ["Melodic Death Metal"],
  },
  {
    artist: "Kalandra",
    album: "A Frame Of Mind",
    rank: "48",
    myRate: "84",
    criticsRate: "90",
    dateRelease: "2024-September-13",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/999791-a-frame-of-mind_191204.jpg",
    spotifyLink: "https://open.spotify.com/album/7tmd1LZ4ZT9eoA4Jl1MNFy",
    genres: ["Folk Rock"],
  },
  {
    artist: "Enterprise Earth",
    album: "Death: An Anthology",
    rank: "49",
    myRate: "84",
    criticsRate: "82",
    dateRelease: "2024-february-2",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/768500-death-an-anthology_0423.jpg",
    spotifyLink: "https://open.spotify.com/album/2JBNKkdKgCZ9mW2IZOuOHd",
    genres: ["Progressive Death Metal"],
  },
  {
    artist: "Groza",
    album: "Nadir",
    rank: "50",
    myRate: "84",
    criticsRate: "NR",
    dateRelease: "2024-September-20",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1000482-nadir_064657.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4RVc6bTkh9SvjeV89Fsep4?si=Q8wj_ed7S0qvbWIQb-hgZA",
    genres: ["Atmospheric Black Metal"],
  },
  {
    artist: "Spectral Wound",
    album: "Songs of Blood and Mire",
    rank: "51",
    myRate: "83",
    criticsRate: "80",
    dateRelease: "2024-august-23",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/995117-songs-of-blood-and-mire_132624.jpg",
    spotifyLink: "https://open.spotify.com/album/2AljWxmNh0mQPFAKAwKlIt",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "State Faults",
    album: "Children Of The Moon",
    rank: "52",
    myRate: "83",
    criticsRate: "NR",
    dateRelease: "2024-July-26",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/964459-children-of-the-moon_163258.jpg",
    spotifyLink: "https://open.spotify.com/album/7tqqBxs66oVjVvz7a9Isg7",
    genres: ["Post-Hardcore"],
  },
  {
    artist: "Drown In Sulphur",
    album: "Dark Secrets of the Soul",
    rank: "53",
    myRate: "83",
    criticsRate: "65",
    dateRelease: "2024-january-12",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/792059-dark-secrets-of-the-soul_001102.jpg",
    spotifyLink: "https://open.spotify.com/album/2tmOfzN2WPTi2bVk4kcEjZ",
    genres: ["Blackened Death Metal"],
  },
  {
    artist: "Nachtmystium",
    album: "Blight Privilege",
    rank: "54",
    myRate: "83",
    criticsRate: "80",
    dateRelease: "2024-november-1",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1045733-blight-privilege_174924.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6SE1k7LZlvvxY5xTdbvPnD?si=wxBYbl4vTVyXCIEJtdbvHg",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Spider God",
    album: "Possess The Devil",
    rank: "55",
    myRate: "83",
    criticsRate: "60",
    dateRelease: "2024-november-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1132625-possess-the-devil_062043.jpg",
    spotifyLink:
      "https://open.spotify.com/album/0JXj5SrEMZIBrma0Mj3ZPR?si=n04K7oWzT7qkekVhJLvWaQ",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Nails",
    album: "Every Bridge Burning",
    rank: "56",
    myRate: "82",
    criticsRate: "77",
    dateRelease: "2024-august-30",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/678402-every-bridge-burning_180659.jpg",
    spotifyLink: "https://open.spotify.com/album/269SQRalfaebSVSDnIQe1g",
    genres: ["Grindcore"],
  },
  {
    artist: "As I Lay Dying",
    album: "The Void Within",
    rank: "57",
    myRate: "82",
    criticsRate: "NR",
    dateRelease: "2024-October-13",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1131797-the-void-within_131130.jpg",
    spotifyLink:
      "https://open.spotify.com/album/25a3xkHUh4myBSbuWldXZc?si=lRwOrDzuSi-43tNw0_88iA",
    genres: ["Melodic Death Metal"],
    type: "ep",
    epRank: "8",
  },
  {
    artist: "Melted Bodies",
    album: "The Inevitable Fork LP",
    rank: "58",
    myRate: "82",
    criticsRate: "60",
    dateRelease: "2024-October-18",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1048178-the-inevitable-fork-lp_031141.jpg",
    spotifyLink:
      "https://open.spotify.com/album/72rgtqVXEbrQMV1ufHVtpf?si=9YnnZzCcTLGhHcyYrtTt8g",
    genres: ["Avant-Garde Metal"],
  },
  {
    artist: "Uniform",
    album: "American Standard",
    rank: "59",
    myRate: "82",
    criticsRate: "87",
    dateRelease: "2024-august-23",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/997381-american-standard_144329.jpg",
    spotifyLink: "https://open.spotify.com/album/2i6NKvLSPRQVyBwmq7ASGG",
    genres: ["Noise Rock"],
  },
  {
    artist: "Job for a Cowboy",
    album: "Moon Healer",
    rank: "60",
    myRate: "82",
    criticsRate: "84",
    dateRelease: "2024-February-23",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/778749-moon-healer_004536.jpg",
    spotifyLink: "https://open.spotify.com/album/2nYVbfF20AiedBTYcswFAW",
    genres: ["Technical Death Metal"],
  },
  {
    artist: "Blasphemous",
    album: "To Lay Siege And Conquer",
    rank: "61",
    myRate: "82",
    criticsRate: "60",
    dateRelease: "2024-October-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1088575-to-lay-siege-and-conquer_090842.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5YeOdb0XnqryOgaPHj8euL?si=hpv-CMdfSeSrWIRDKMBC8Q",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Rotting Christ",
    album: "Pro Xristou",
    rank: "62",
    myRate: "81",
    criticsRate: "76",
    dateRelease: "2024-May-24",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/852023-pro-xristou_131656.jpg",
    spotifyLink: "https://open.spotify.com/album/3oXblizhnWNqlsWJrpagaB",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Aborted",
    album: "Vault of Horrors",
    rank: "63",
    myRate: "81",
    criticsRate: "77",
    dateRelease: "2024-march-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/844881-vault-of-horrors_164703.jpg",
    spotifyLink: "https://open.spotify.com/album/7yEhJNdsi60V7iBxHiVAWE",
    genres: ["Brutal Death Metal"],
  },
  {
    artist: "200 Stab Wounds",
    album: "Manual Manic Procedures",
    rank: "64",
    myRate: "81",
    criticsRate: "83",
    dateRelease: "2024-June-28",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/939652-manual-manic-procedures_154341.jpg",
    spotifyLink: "https://open.spotify.com/album/2p4qPInJmmYl8QZ3uhIbDb",
    genres: ["Brutal Death Metal"],
  },
  {
    artist: "Heriot",
    album: "Devoured by the Mouth of Hell",
    rank: "65",
    myRate: "81",
    criticsRate: "88",
    dateRelease: "2024-september-27",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/977580-devoured-by-the-mouth-of-hell_161225.jpg",
    spotifyLink: "https://open.spotify.com/album/4vZr6vNAUHUjLNmbjGI62l",
    genres: ["Atmospheric Sludge Metal"],
  },
  {
    artist: "Marilyn Manson",
    album: "One Assassination Under God - Chapter 1",
    rank: "66",
    myRate: "81",
    criticsRate: "85",
    dateRelease: "2024-november-22",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1085093-one-assassination-under-god-chapter-1_184714.jpg",
    spotifyLink: "https://open.spotify.com/album/16PEiWfVzjHWJ6i8nGtfLd",
    genres: ["Industrial Metal"],
  },
  {
    artist: "Livløs",
    album: "The Crescent King",
    rank: "67",
    myRate: "81",
    criticsRate: "NR",
    dateRelease: "2024-october-4",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/965419-the-cresent-king_090255.jpg",
    spotifyLink:
      "https://open.spotify.com/album/2GfBm0Qn2nDmCMpKjMgegX?si=6nuP5504Qn6etBlvNmgRag",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Illdisposed",
    album: "In Chambers Of Sonic Disgust",
    rank: "68",
    myRate: "81",
    criticsRate: "50",
    dateRelease: "2024-june-28",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/960790-in-chambers-of-sonic-disgust_200528.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6tYsCDcXuWpQuzkESOdHAb?si=J9yeVMU4TsS8N2K9BLdYIA",
    genres: ["Melodic Death Metal"],
  },
  {
    artist: "Firtan",
    album: "Ethos",
    rank: "69",
    myRate: "80",
    criticsRate: "70",
    dateRelease: "2024-September-13",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1008612-ethos_105818.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5nYG4TohecIyWglPD836nT?si=ZXFHf69HTYm5j97MLpgYiQ",
    genres: ["Atmospheric Black Metal"],
  },
  {
    artist: "Knocked Loose",
    album: "You Won't Go Before You're Supposed To",
    rank: "70",
    myRate: "80",
    criticsRate: "88",
    dateRelease: "2024-May-24",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/887049-you-wont-go-before-youre-supposed-to_185001.jpg",
    spotifyLink: "https://open.spotify.com/album/2sLBMdUF5HYNB0voqWs4K3",
    genres: ["Metalcore"],
  },
  {
    artist: "Recidivist",
    album: "Madness Malformed",
    rank: "71",
    myRate: "80",
    criticsRate: "NR",
    dateRelease: "2024-November-1",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1120497-madness-malformed_203522.jpg",
    spotifyLink:
      "https://open.spotify.com/album/0S5ErGtOf5qen0LDn3iQrk?si=jQ-Y4limSJy7qfI957Jq5A",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Ingurgitating Oblivion",
    album: "Ontology of Nought",
    rank: "72",
    myRate: "80",
    criticsRate: "70",
    dateRelease: "2024-september-27",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1039974-ontology-of-nought_134050.jpg",
    spotifyLink:
      "https://open.spotify.com/album/1xJ3AfTOdsBltWGFDubJZ9?si=x1iFFV92SfSkP-1DKrysew",
    genres: ["Avant-Garde Metal"],
  },
  {
    artist: "MIRAR",
    album: "Mare",
    rank: "73",
    myRate: "80",
    criticsRate: "80",
    dateRelease: "2024-June-10",
    cover: "https://cdn2.albumoftheyear.org/375x/album/981914-mare_160049.jpg",
    spotifyLink: "https://open.spotify.com/album/7MDMBadUvE61SEwGapi43t",
    genres: ["Avant-Garde Metal"],
    type: "ep",
    epRank: "9",
  },
  {
    artist: "Alcest",
    album: "Les Chants de l'Aurore",
    rank: "74",
    myRate: "80",
    criticsRate: "80",
    dateRelease: "2024-june-21",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/882830-les-chants-de-laurore_155157.jpg",
    spotifyLink: "https://open.spotify.com/album/24nGcIMJdnThRbgxpovlpy",
    genres: ["Post-Metal"],
  },
  {
    artist: "The Fallen Prophets",
    album: "Primordial Instinct",
    rank: "75",
    myRate: "80",
    criticsRate: "NR",
    dateRelease: "2024-November-1",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1093050-primordial-instinct_041845.jpg",
    spotifyLink:
      "https://open.spotify.com/album/0x3rQdmKj9zukC0GERIway?si=0pkdhRaeTpKM8Hl_ovhioA",
    genres: ["Brutal Death Metal"],
  },
  {
    artist: "The Black Dahlia Murder",
    album: "Servitude",
    rank: "76",
    myRate: "79",
    criticsRate: "79",
    dateRelease: "2024-september-27",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/983814-servitude_040552.jpg",
    spotifyLink: "https://open.spotify.com/album/0undBsA6pQzjKX3GBH2gq5",
    genres: ["Melodic Death Metal"],
  },
  {
    artist: "fallingwithscissors",
    album: "the death and birth of an angel",
    rank: "77",
    myRate: "79",
    criticsRate: "NR",
    dateRelease: "2024-january-11",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/844693-the-death-and-birth-of-an-angel_131524.jpg",
    spotifyLink: "https://open.spotify.com/album/7IqFNvvRivT4ZNti8mJcm7",
    genres: ["Metalcore"],
    type: "ep",
    epRank: "10",
  },
  {
    artist: "Caligula's Horse",
    album: "Charcoal Grace",
    rank: "78",
    myRate: "79",
    criticsRate: "80",
    dateRelease: "2024-january-26",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/791937-charcoal-grace_200552.jpg",
    spotifyLink: "https://open.spotify.com/album/2XZiBGEBzo5PqSMjgGV6IS",
    genres: ["Progressive Metal"],
  },
  {
    artist: "The Last Ten Seconds Of Life",
    album: "No Name Graves",
    rank: "79",
    myRate: "79",
    criticsRate: "75",
    dateRelease: "2024-february-9",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/867585-no-name-graves_122825.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5e4EUEcJ1CBfNGmPY9EGf7?si=0yxfAKxyQMSM5dJ6XPRkHg",
    genres: ["Deathcore"],
  },
  {
    artist: "Make Them Suffer",
    album: "Make Them Suffer",
    rank: "80",
    myRate: "78",
    criticsRate: "72",
    dateRelease: "2024-november-8",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1041179-make-them-suffer_203511.jpg",
    spotifyLink: "https://open.spotify.com/album/4IlFCPiC0DlO0wip7BjQwr",
    genres: ["Metalcore"],
  },
  {
    artist: "Salem Trials",
    album: "Rot",
    rank: "81",
    myRate: "79",
    criticsRate: "NR",
    dateRelease: "2024-september-27",
    cover: "https://cdn2.albumoftheyear.org/375x/album/1054634-rot_040502.jpg",
    spotifyLink:
      "https://open.spotify.com/album/3WqgcCt0wxopJQpHi1Xbcn?si=Askz2RBWSiyIjT8Kzi_yuw",
    genres: ["Deathcore"],
  },
  {
    artist: "Better Lovers",
    album: "Highly Irresponsible",
    rank: "82",
    myRate: "78",
    criticsRate: "79",
    dateRelease: "2024-october-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1031888-highly-irresponsible_013817.jpg",
    spotifyLink: "https://open.spotify.com/album/3exRH9T55nlwQ2JffTYkSZ",
    genres: ["Metalcore"],
  },
  {
    artist: "Cane Hill",
    album: "A Piece Of Me I Never Let You Find",
    rank: "83",
    myRate: "78",
    criticsRate: "80",
    dateRelease: "2024-november-1",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1025806-a-piece-of-me-i-never-let-you-find_131750.jpg",
    spotifyLink:
      "https://open.spotify.com/album/1yh863utXtpMuPlIbzM2Uh?si=heOOOEWlT5CFQcTiEPBcxA",
    genres: ["Metalcore"],
  },
  {
    artist: "Opeth",
    album: "The Last Will and Testament",
    rank: "84",
    myRate: "78",
    criticsRate: "84",
    dateRelease: "2024-november-22",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1034622-the-last-will-and-testament_215629.jpg",
    spotifyLink: "https://open.spotify.com/album/1f2Q8urIhVZiuPSiNLcQG6",
    genres: ["Progressive Death Metal"],
  },
  {
    artist: "Poppy",
    album: "Negative Spaces",
    rank: "85",
    myRate: "77",
    criticsRate: "79",
    dateRelease: "2024-november-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1083403-negative-spaces_160415.jpg",
    spotifyLink: "https://open.spotify.com/album/0YIOpXQvcbiDNPusSqi5Ew",
    genres: ["Metalcore"],
  },
  {
    artist: "High Parasite",
    album: "Forever We Burn",
    rank: "86",
    myRate: "77",
    criticsRate: "75",
    dateRelease: "2024-september-27",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/989102-forever-we-burn_230451.jpg",
    spotifyLink:
      "https://open.spotify.com/album/35PPUdDdkAcrvUZ3p9rQjB?si=Z5QpLuA4SgCbLeQEXkZRUw",
    genres: ["Metalcore"],
  },
  {
    artist: "Tribulation",
    album: "Sub Rosa in Æternum",
    rank: "87",
    myRate: "77",
    criticsRate: "79",
    dateRelease: "2024-november-1",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1071262-sub-rosa-in-aeternum_080440.jpg",
    spotifyLink: "https://open.spotify.com/album/37FOQdanrC3La3Fg3cT25P",
    genres: ["Gothic Metal"],
  },
  {
    artist: "Enforced",
    album: "A Leap Into The Dark",
    rank: "88",
    myRate: "77",
    criticsRate: "74",
    dateRelease: "2024-october-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1088571-a-leap-into-the-dark_090516.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6rqhnhCNfczNN9BzSuUleK?si=98Smx2h2S_-M8Gf1njvXrQ",
    genres: ["Death Thrash Metal"],
  },
  {
    artist: "Mother Of Graves",
    album: "The Periapt Of Absence",
    rank: "89",
    myRate: "76",
    criticsRate: "90",
    dateRelease: "2024-october-18",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1054109-the-periapt-of-absence_181216.jpg",
    spotifyLink:
      "https://open.spotify.com/album/7GyjcArJ1sbnRqCuNDPlsl?si=OvHo36C0Qm2aYEcl5R93Qg",
    genres: ["Death Doom Metal"],
  },
  {
    artist: "Nightwish",
    album: "Yesterwynde",
    rank: "90",
    myRate: "76",
    criticsRate: "86",
    dateRelease: "2024-september-20",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/945279-yesterwynde_161138.jpg",
    spotifyLink: "https://open.spotify.com/album/39CVUoSmw8915LRClkNH0o",
    genres: ["Symphonic Metal"],
  },
  {
    artist: "Ripped To Shreds",
    album: "Sanshi",
    rank: "91",
    myRate: "76",
    criticsRate: "83",
    dateRelease: "2024-september-27",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1032596-sanshi_151029.jpg",
    spotifyLink: "https://open.spotify.com/album/3yH6gKLL06D59p80yjmhq1",
    genres: ["Death Metal"],
  },
  {
    artist: "Trhä",
    album: "∫um'ad∂ejja cavvaj",
    rank: "92",
    myRate: "76",
    criticsRate: "NR",
    dateRelease: "2024-august-1",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1034260-umadejja-cavvaj_144943.jpg",
    spotifyLink: "https://open.spotify.com/album/2MsbvlWVMA9aBhzBzs85M2",
    genres: ["Atmospheric Black Metal"],
  },
  {
    artist: "Jerry Cantrell",
    album: "I Want Blood",
    rank: "93",
    myRate: "75",
    criticsRate: "79",
    dateRelease: "2024-october-18",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1028422-i-want-blood_063449.jpg",
    spotifyLink: "https://open.spotify.com/album/1clodpcGPsGi0DAwIUHh8L",
    genres: ["Alternative Metal"],
  },
  {
    artist: "1349",
    album: "The Wolf and the King",
    rank: "94",
    myRate: "75",
    criticsRate: "82",
    dateRelease: "2024-october-4",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1012108-the-wolf-and-the-king_211332.jpg",
    spotifyLink: "https://open.spotify.com/album/6TFhglZUGyU8h4FWyfOi6o",
    genres: ["Black Metal"],
  },
  {
    artist: "Mork",
    album: "Syv",
    rank: "95",
    myRate: "75",
    criticsRate: "81",
    dateRelease: "2024-september-20",
    cover: "https://cdn2.albumoftheyear.org/375x/album/1025900-syv_154615.jpg",
    spotifyLink: "https://open.spotify.com/album/4VqgfAUio1PNXUpm5BhzB2",
    genres: ["Black Metal"],
  },
  {
    artist: "Falling In Reverse",
    album: "Popular Monster",
    rank: "96",
    myRate: "75",
    criticsRate: "50",
    dateRelease: "2024-august-16",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/951249-popular-monster_145605.jpg",
    spotifyLink: "https://open.spotify.com/album/2knEuvsxqHMAoxlQpIdpQD",
    genres: ["Metalcore"],
  },
  {
    artist: "Vended",
    album: "Vended",
    rank: "97",
    myRate: "74",
    criticsRate: "78",
    dateRelease: "2024-september-20",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1032489-vended_132838.jpg",
    spotifyLink: "https://open.spotify.com/album/2tDnVMI6pBlsiEMOfb5DaU",
    genres: ["Metalcore"],
  },
  {
    artist: "Cats Season",
    album: "Revolution",
    rank: "98",
    myRate: "72",
    criticsRate: "NR",
    dateRelease: "2024-september-21",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1087166-revolution_194916.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6yMaQsLUyuiEvAED3uMBdC?si=5fhLUfI5TrSD_sS7LWw2jA",
    genres: ["Deathcore"],
  },
  {
    artist: "Bring Me The Horizon",
    album: "POST HUMAN: NeX GEn",
    rank: "99",
    myRate: "65",
    criticsRate: "73",
    dateRelease: "2024-may-24",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/681928-post-human-nex-gen_191848.jpg",
    spotifyLink: "https://open.spotify.com/album/1k7OXnGQPV4zF3seDwRroD",
    genres: ["Alternative Metal"],
  },
  {
    artist: "Linkin Park",
    album: "From Zero",
    rank: "100",
    myRate: "45",
    criticsRate: "73",
    dateRelease: "2024-november-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1067322-from-zero_220219.jpg",
    spotifyLink: "https://open.spotify.com/album/4R6FV9NSzhPihHR0h4pI93",
    genres: ["Alternative Rock"],
  },
];

export const rapAlbums = [
  {
    artist: "Quadeca",
    album: "SCRAPYARD",
    rank: "1",
    myRate: "100",
    criticsRate: "90",
    dateRelease: "2024-February-16",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/868978-scrapyard_140214.jpg",
    spotifyLink:
      "https://open.spotify.com/album/2uoD60Oip7rq3vjXxZ2VaD?si=47HCcRhDQLOvrKRKteFe_Q",
    genres: ["Experimental Hip Hop", "Art Pop"],
  },
  {
    artist: "JPEGMAFIA",
    album: "I LAY DOWN MY LIFE FOR YOU",
    rank: "2",
    myRate: "100",
    criticsRate: "78",
    dateRelease: "2024-August-1",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/1028788-i-lay-down-my-life-for-you_144318.jpg",
    spotifyLink:
      "https://open.spotify.com/album/1ezs1QD5SYQ6LtxpC9y5I2?si=AV4dcDNYSpu_ph22QBxwhQ",
    genres: ["Experimental Hip Hop", "Hardcore Hip Hop"],
  },
  {
    artist: "Gao the Arsonist",
    album: "AND THEY MINE FOR OUR BODIES",
    rank: "3",
    myRate: "100",
    criticsRate: "82",
    dateRelease: "2024-October-18",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/1079995-and-they-mine-for-our-bodies_203935.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6PwC4A9kdUcsxdT0C9UO6p?si=hqjN3uLRSPaaRilzpQH-rg",
    genres: ["Experimental Hip Hop", "Emo Rap", "Industrial Hip Hop"],
  },
  {
    artist: "Vince Staples",
    album: "Dark Times",
    rank: "4",
    myRate: "85",
    criticsRate: "82",
    dateRelease: "2024-May-24",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/961934-dark-times_205543.jpg",
    spotifyLink:
      "https://open.spotify.com/album/30BFY5VHii4PyWqkTubUWX?si=LTfBmv8dQeq2agmZbjRXbg",
    genres: ["Conscious Hip Hop", "West Coast Hip Hop"],
  },
  {
    artist: "ScHoolboy Q",
    album: "BLUE LIPS",
    rank: "5",
    myRate: "85",
    criticsRate: "81",
    dateRelease: "2024-March-1",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/863982-blue-lips_131012.jpg",
    spotifyLink:
      "https://open.spotify.com/album/107WsrBqn5xVPgystkziry?si=GDsGgvSIQHGxPAz9JY9dwA",
    genres: ["West Coast Hip Hop", "Hardcore Hip Hop"],
  },
  {
    artist: "Ka",
    album: "The Thief Next to Jesus",
    rank: "6",
    myRate: "85",
    criticsRate: "86",
    dateRelease: "2024-August-19",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/1011890-the-thief-next-to-jesus_181340.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4fmC67uHti9BxWUNAUb6wy?si=wpAHTsu1RTusvJ_G7Tq4vA",
    genres: ["Abstract Hip Hop", "Drumless", "East Coast Hip Hop"],
  },
  {
    artist: "Mach-Hommy",
    album: "#RICHAXXHAITIAN",
    rank: "7",
    myRate: "85",
    criticsRate: "83",
    dateRelease: "2024-May-17",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/676662-richaxxhaitian_1025.jpg",
    spotifyLink:
      "https://open.spotify.com/album/3akQbvTaRFTiQYZILxVm3E?si=UMOqvK9lT42OdOm2oNDDCg",
    genres: ["Abstract Hip Hop", "East Coast Hip Hop"],
  },
  {
    artist: "Bladee",
    album: "Cold Visions",
    rank: "8",
    myRate: "85",
    criticsRate: "67",
    dateRelease: "2024-April-24",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/938851-coldvisions_174054.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5fjDXtY8tws1sbPFHw34pL?si=kJ9Yu7jiSfinW6N_vmipnQ",
    genres: ["Rage", "Tread"],
  },
  {
    artist: "Lupe Fiasco",
    album: "Samurai",
    rank: "9",
    myRate: "85",
    criticsRate: "81",
    dateRelease: "2024-June-28",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/939552-samurai_112616.jpg",
    spotifyLink:
      "https://open.spotify.com/album/1O6d4cNuUV78GeXv7hgr4e?si=50GfAqq7SL2zy-epnQKiNg",
    genres: ["Jazz Rap", "Abstract Hip Hop"],
  },
  {
    artist: "DC The Don",
    album: "REBIRTH",
    rank: "10",
    myRate: "80",
    criticsRate: "76",
    dateRelease: "2024-October-23",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/702078-rebirth_130428.jpg",
    spotifyLink:
      "https://open.spotify.com/album/3bvzvApxQGgI1VX4jSD86G?si=DX3qMHeASD-88X64sHCygQ",
    genres: ["Pop Rap", "Trap"],
  },
  {
    artist: "Tyler, The Creator",
    album: "CHROMAKOPIA",
    rank: "11",
    myRate: "80",
    criticsRate: "83",
    dateRelease: "2024-October-28",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/1104481-chromakopia_090343.jpg",
    spotifyLink:
      "https://open.spotify.com/album/0U28P0QVB1QRxpqp5IHOlH?si=RB3gsXRQTp-GKLe6MO2rJg",
    genres: ["Experimental Hip Hop", "West Coast Hip Hop"],
  },
  {
    artist: "Future & Metro Boomin",
    album: "WE DON'T TRUST YOU",
    rank: "12",
    myRate: "80",
    criticsRate: "62",
    dateRelease: "2024-March-22",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/896934-we-dont-trust-you_143101.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4iqbFIdGOTzXeDtt9owjQn?si=DLwua_LQTg-qTy6r0tn-0w",
    genres: ["Trap", "Southern Hip Hop"],
  },
  {
    artist: "Doechii",
    album: "Alligator Bites Never Heal",
    rank: "13",
    myRate: "80",
    criticsRate: "74",
    dateRelease: "2024-August-30",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/1046815-alligator-bites-never-heal_173058.jpg",
    spotifyLink:
      "https://open.spotify.com/album/60UzB8mOCMpc7xkuJE6Bwc?si=3oKWdNMkRKKAWfm42mG81Q",
    genres: ["Southern Hip Hop", "Boom Bap"],
  },
  {
    artist: "MIKE & Tony Seltzer",
    album: "Pinball",
    rank: "14",
    myRate: "80",
    criticsRate: "80",
    dateRelease: "2024-March-6",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/893168-pinball_132926.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5gHqM8u3IclJ1ZV6q309OW?si=poOTH0_KT9etIGHK2vjFUw",
    genres: ["Abstract Hip Hop", "Trap", "East Coast Hip Hop"],
  },
  {
    artist: "Denzel Curry",
    album: "KING OF THE MISCHIEVOUS SOUTH",
    rank: "15",
    myRate: "80",
    criticsRate: "77",
    dateRelease: "2024-November-15",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/1041160-king-of-the-mischievous-south-vol-2-deluxe_231238.jpg",
    spotifyLink:
      "https://open.spotify.com/album/1OUX2HxH2tyqyHMALnYbnG?si=4PvliPrLSOSxPxeYw1sV-A",
    genres: ["Southern Hip Hop", "Trap", "Memphis Rap"],
  },
  {
    artist: "Yeat",
    album: "2093",
    rank: "16",
    myRate: "80",
    criticsRate: "65",
    dateRelease: "2024-February-17",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/878483-2093-p2_120134.jpg",
    spotifyLink:
      "https://open.spotify.com/album/7aUeYDjGYo8wMKcpeGFRbg?si=2ghBt7OXTZS-kCSt_peidA",
    genres: ["Experimental Hip Hop", "Rage", "Industrial Hip Hop"],
  },
  {
    artist: "Boldy James & Conductor Williams",
    album: "Across The Tracks",
    rank: "17",
    myRate: "75",
    criticsRate: "78",
    dateRelease: "2024-June-28",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/965077-across-the-tracks_124057.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4vGxWRaA3iG6w8st1eOtlt?si=fTJql4HVQmSNZZa9ygnshg",
    genres: ["Gangsta Rap", "Boom Bap", "Coke Rap"],
  },
  {
    artist: "Kendrick Lamar",
    album: "GNX",
    rank: "18",
    myRate: "75",
    criticsRate: "87",
    dateRelease: "2024-November-22",
    cover: "https://cdn2.albumoftheyear.org/750x/album/1139965-gnx_174958.jpg",
    spotifyLink:
      "https://open.spotify.com/album/0hvT3yIEysuuvkK73vgdcW?si=RBzaR9b8RTCec-VsvEsIfQ",
    genres: ["West Coast Hip Hop", "Trap"],
  },
  {
    artist: "Logic",
    album: "Ultra 85",
    rank: "19",
    myRate: "75",
    criticsRate: "85",
    dateRelease: "2024-August-9",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/833847-ultra-85_171909.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6vVOpqIXPbM9vZWzesdTax?si=DkDCGU1gQUCv13aHH45LbA",
    genres: ["Boom Bap", "East Coast Hip Hop", "Conscious Hip Hop"],
  },
  {
    artist: "MAVI",
    album: "shadowbox",
    rank: "20",
    myRate: "75",
    criticsRate: "80",
    dateRelease: "2024-August-9",
    cover:
      "https://cdn2.albumoftheyear.org/750x/album/990020-shadowbox_142521.jpg",
    spotifyLink:
      "https://open.spotify.com/album/3rGKeVhGWOwBzodSU6zBXQ?si=0JshpnV2S3y0OjRoQy6eKQ",
    genres: ["Abstract Hip Hop", "Conscious Hip Hop"],
  },
];
