export const albums = [
  {
    artist: "Kanonenfieber",
    album: "Die Urkatastrophe",
    rank: "1",
    myRate: "100",
    criticsRate: "90",
    dateRelease: "2024-September-20",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/984930-die-urkatastrophe_122510.jpg",
    spotifyLink: "https://open.spotify.com/album/15cBVOLGxioRUCDrkcLiAr",
    genres: ["Black Metal", "Melodic Black Metal", "Blackened Death Metal"],
  },
  {
    artist: "Gaerea",
    album: "Coma",
    rank: "2",
    myRate: "99",
    criticsRate: "83",
    dateRelease: "2024-October-25",
    cover: "https://cdn2.albumoftheyear.org/375x/album/1019321-coma_091656.jpg",
    spotifyLink: "https://open.spotify.com/album/4i9i7I98VBon2pJOWBtbX1",
    genres: [
      "Black Metal",
      "Atmospheric Black Metal",
      "Melodic Death Metal",
      "Post Black Metal",
    ],
  },
  {
    artist: "Disembodied Tyrant & Synestia",
    album: "The Poetic Edda",
    rank: "3",
    myRate: "98",
    criticsRate: "NR",
    dateRelease: "2024-May-03",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/688127-the-poetic-edda_0046.jpg",
    spotifyLink: "https://open.spotify.com/album/3AO82S43rn68Vk4FLgNXKp",
    genres: ["Deathcore", "Symphonic Deathcore", "Neoclassical Metal"],
  },
  {
    artist: "Fit for an Autopsy",
    album: "The Nothing That Is",
    rank: "4",
    myRate: "97",
    criticsRate: "77",
    dateRelease: "2024-October-25",
    description: "",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1025833-the-nothing-that-is_141102.jpg",
    spotifyLink: "https://open.spotify.com/album/4ZYfWm41dWgewV1yMV4zmU",
    genres: ["Deathcore", "Groove Metal", "Djent"],
  },
  {
    artist: "Iotunn",
    album: "Kinship",
    rank: "5",
    myRate: "96",
    criticsRate: "88",
    dateRelease: "2024-October-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1062107-kinship_125657.jpg",
    spotifyLink: "https://open.spotify.com/album/2XS9Fdf7FWNhWp4zlveMHC",
    genres: ["Progressive Metal", "Melodic Death Metal"],
  },
  {
    artist: "Akhlys",
    album: "House of the Black Geminus",
    rank: "6",
    myRate: "96",
    criticsRate: "NR",
    dateRelease: "2024-july-5",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/922140-house-of-the-black-geminus_153204.jpg",
    spotifyLink: "https://open.spotify.com/album/2hzBIujiK4PM4Vs0PpWfju",
    genres: ["Atmospheric Black Metal", "Horrorcore", "Dark Ambient"],
  },
  {
    artist: "Ulcerate",
    album: "Cutting the Throat of God",
    rank: "7",
    myRate: "95",
    criticsRate: "88",
    dateRelease: "2024-june-14",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/901868-cutting-the-throat-of-god_225949.jpg",
    spotifyLink: "https://open.spotify.com/album/2QNcQNDeIvL0EWOSP87iSm",
    genres: [
      "Technical Death Metal",
      "Dissonant Death Metal",
      "Atmospheric Sludge Metal",
    ],
  },
  {
    artist: "wormwood",
    album: "The Star",
    rank: "8",
    myRate: "95",
    criticsRate: "40",
    dateRelease: "2024-May-31",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/876824-the-star_110836.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5LJYblFx6TQQkXpmFnid89?si=o0C-P-XqTYK1_XI_HqdAiw",
    genres: ["Melodic Black Metal", "Atmospheric Black Metal"],
  },
  {
    artist: "Crippling Alcoholism",
    album: "With Love from a Padded Room",
    rank: "9",
    myRate: "94",
    criticsRate: "NR",
    dateRelease: "2024-February-29",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/898296-with-love-from-a-padded-room_043706.jpg",
    spotifyLink: "https://open.spotify.com/album/0RtIISlw4JR8qucHOgaulK",
    genres: ["Gothic Rock", "Post Metal", "Darkwave"],
  },
  {
    artist: "Panzerfaust",
    album: "The Suns of Perdition IV: To Shadow Zion",
    rank: "10",
    myRate: "94",
    criticsRate: "80",
    dateRelease: "2024-November-22",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1079656-the-suns-of-perdition-iv-to-shadow-zion_143121.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4qvtmdzVR2uRie3dVhMZtM?si=hJ2CFxJqRb2wdyH9p-b_Hg",
    genres: ["Black Metal", "Atmospheric Black Metal"],
  },
  {
    artist: "Uboa",
    album: "Impossible Light",
    rank: "11",
    myRate: "93",
    criticsRate: "NR",
    dateRelease: "2024-june-28",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/998246-impossible-light_020319.jpg",
    spotifyLink: "https://open.spotify.com/album/1ZwJMEEaBifkdvQl793ek3",
    genres: [
      "Death Industrial",
      "Dark Ambient",
      "Post Metal",
      "Neoclassical Darkwave",
    ],
  },
  {
    artist: "Oceano",
    album: "Living Chaos",
    rank: "12",
    myRate: "93",
    criticsRate: "77",
    dateRelease: "2024-august-30",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/978419-living-chaos_161151.jpg",
    spotifyLink: "https://open.spotify.com/album/3exzrDKmQgQVJFtbiiBZi6",
    genres: ["Deathcore"],
  },
  {
    artist: "Blood Incantation",
    album: "Absolute Elsewhere",
    rank: "13",
    myRate: "92",
    criticsRate: "87",
    dateRelease: "2024-october-4",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/997344-absolute-elsewhere_141614.jpg",
    spotifyLink: "https://open.spotify.com/album/7hriIeLMviZKpNfcXgpsd8",
    genres: ["Progressive Death Metal", "Technical Deaths Metal"],
  },
  {
    artist: "Fleshgod Apocalypse",
    album: "Opera",
    rank: "14",
    myRate: "92",
    criticsRate: "87",
    dateRelease: "2024-August-23",
    cover: "https://cdn2.albumoftheyear.org/375x/album/984612-opera_040704.jpg",
    spotifyLink: "https://open.spotify.com/album/1dDS9EG35qdgeshBzEP2ja",
    genres: ["Technical Deaths Metal", "Symphonic Metal", "Neoclassical Metal"],
  },
  {
    artist: "Psychonaut 4",
    album: "…Of Mourning",
    rank: "15",
    myRate: "92",
    criticsRate: "NR",
    dateRelease: "2024-October-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1051676-of-mourning_020923.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5SCmr0N6XlXf3s7cohLt4k?si=cLwcT3v-QXuiNExeOngwpg",
    genres: ["DSBM", "Black Metal", "Atmospheric Black Metal"],
  },
  {
    artist: "Ihsahn",
    album: "IHSAHN",
    rank: "16",
    myRate: "92",
    criticsRate: "85",
    dateRelease: "2024-February-16",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/797214-ihsahn_130727.jpg",
    spotifyLink: "https://open.spotify.com/album/78eWgdCbll6LBKZR696IBE",
    genres: [
      "Symphonic Metal",
      "Black Metal",
      "Symphonic Black Metal",
      "Progressive Metal",
    ],
  },
  {
    artist: "Immortal Disfigurement",
    album: "KING",
    rank: "17",
    myRate: "92",
    criticsRate: "NR",
    dateRelease: "2024-June-7",
    cover: "https://cdn2.albumoftheyear.org/375x/album/979592-king_181006.jpg",
    spotifyLink:
      "https://open.spotify.com/album/2aHlXLfPMPWlGr248ZeR7E?si=BKPlLW0ZRxW-u3ciH8zQ2Q",
    genres: ["Deathcore", "Symphonic Metal"],
  },
];
