export const albums = [
  {
    artist: "Kanonenfieber",
    album: "Die Urkatastrophe",
    rank: "1",
    myRate: "100",
    criticsRate: "90",
    dateRelease: "2024-September-20",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/984930-die-urkatastrophe_122510.jpg",
    spotifyLink: "https://open.spotify.com/album/15cBVOLGxioRUCDrkcLiAr",
    genres: ["Black Metal", "Melodic Black Metal", "Blackened Death Metal"],
  },
  {
    artist: "Gaerea",
    album: "Coma",
    rank: "2",
    myRate: "99",
    criticsRate: "83",
    dateRelease: "2024-October-25",
    cover: "https://cdn2.albumoftheyear.org/375x/album/1019321-coma_091656.jpg",
    spotifyLink: "https://open.spotify.com/album/4i9i7I98VBon2pJOWBtbX1",
    genres: [
      "Black Metal",
      "Atmospheric Black Metal",
      "Melodic Death Metal",
      "Post Black Metal",
    ],
  },
  {
    artist: "Disembodied Tyrant & Synestia",
    album: "The Poetic Edda",
    rank: "3",
    myRate: "98",
    criticsRate: "NR",
    dateRelease: "2024-May-03",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/688127-the-poetic-edda_0046.jpg",
    spotifyLink: "https://open.spotify.com/album/3AO82S43rn68Vk4FLgNXKp",
    genres: ["Deathcore", "Symphonic Deathcore", "Neoclassical Metal"],
  },
  {
    artist: "Fit for an Autopsy",
    album: "The Nothing That Is",
    rank: "4",
    myRate: "97",
    criticsRate: "77",
    dateRelease: "2024-October-25",
    description: "",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1025833-the-nothing-that-is_141102.jpg",
    spotifyLink: "https://open.spotify.com/album/4ZYfWm41dWgewV1yMV4zmU",
    genres: ["Deathcore", "Groove Metal", "Djent"],
  },
  {
    artist: "Iotunn",
    album: "Kinship",
    rank: "5",
    myRate: "96",
    criticsRate: "88",
    dateRelease: "2024-October-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1062107-kinship_125657.jpg",
    spotifyLink: "https://open.spotify.com/album/2XS9Fdf7FWNhWp4zlveMHC",
    genres: ["Progressive Metal", "Melodic Death Metal"],
  },
  {
    artist: "Akhlys",
    album: "House of the Black Geminus",
    rank: "6",
    myRate: "96",
    criticsRate: "NR",
    dateRelease: "2024-july-5",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/922140-house-of-the-black-geminus_153204.jpg",
    spotifyLink: "https://open.spotify.com/album/2hzBIujiK4PM4Vs0PpWfju",
    genres: ["Atmospheric Black Metal", "Horrorcore", "Dark Ambient"],
  },
  {
    artist: "Ulcerate",
    album: "Cutting the Throat of God",
    rank: "7",
    myRate: "95",
    criticsRate: "88",
    dateRelease: "2024-june-14",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/901868-cutting-the-throat-of-god_225949.jpg",
    spotifyLink: "https://open.spotify.com/album/2QNcQNDeIvL0EWOSP87iSm",
    genres: [
      "Technical Death Metal",
      "Dissonant Death Metal",
      "Atmospheric Sludge Metal",
    ],
  },
  {
    artist: "wormwood",
    album: "The Star",
    rank: "8",
    myRate: "95",
    criticsRate: "40",
    dateRelease: "2024-May-31",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/876824-the-star_110836.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5LJYblFx6TQQkXpmFnid89?si=o0C-P-XqTYK1_XI_HqdAiw",
    genres: ["Melodic Black Metal", "Atmospheric Black Metal"],
  },
  {
    artist: "Crippling Alcoholism",
    album: "With Love from a Padded Room",
    rank: "9",
    myRate: "94",
    criticsRate: "NR",
    dateRelease: "2024-February-29",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/898296-with-love-from-a-padded-room_043706.jpg",
    spotifyLink: "https://open.spotify.com/album/0RtIISlw4JR8qucHOgaulK",
    genres: ["Gothic Rock", "Post Metal", "Darkwave"],
  },
  {
    artist: "Panzerfaust",
    album: "The Suns of Perdition IV: To Shadow Zion",
    rank: "10",
    myRate: "94",
    criticsRate: "80",
    dateRelease: "2024-November-22",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1079656-the-suns-of-perdition-iv-to-shadow-zion_143121.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4qvtmdzVR2uRie3dVhMZtM?si=hJ2CFxJqRb2wdyH9p-b_Hg",
    genres: ["Black Metal", "Atmospheric Black Metal"],
  },
  {
    artist: "Uboa",
    album: "Impossible Light",
    rank: "11",
    myRate: "93",
    criticsRate: "NR",
    dateRelease: "2024-june-28",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/998246-impossible-light_020319.jpg",
    spotifyLink: "https://open.spotify.com/album/1ZwJMEEaBifkdvQl793ek3",
    genres: [
      "Death Industrial",
      "Dark Ambient",
      "Post Metal",
      "Neoclassical Darkwave",
    ],
  },
  {
    artist: "Oceano",
    album: "Living Chaos",
    rank: "12",
    myRate: "93",
    criticsRate: "77",
    dateRelease: "2024-august-30",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/978419-living-chaos_161151.jpg",
    spotifyLink: "https://open.spotify.com/album/3exzrDKmQgQVJFtbiiBZi6",
    genres: ["Deathcore"],
  },
  {
    artist: "Blood Incantation",
    album: "Absolute Elsewhere",
    rank: "13",
    myRate: "92",
    criticsRate: "87",
    dateRelease: "2024-october-4",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/997344-absolute-elsewhere_141614.jpg",
    spotifyLink: "https://open.spotify.com/album/7hriIeLMviZKpNfcXgpsd8",
    genres: ["Progressive Death Metal", "Technical Deaths Metal"],
  },
  {
    artist: "Fleshgod Apocalypse",
    album: "Opera",
    rank: "14",
    myRate: "92",
    criticsRate: "87",
    dateRelease: "2024-August-23",
    cover: "https://cdn2.albumoftheyear.org/375x/album/984612-opera_040704.jpg",
    spotifyLink: "https://open.spotify.com/album/1dDS9EG35qdgeshBzEP2ja",
    genres: ["Technical Deaths Metal", "Symphonic Metal", "Neoclassical Metal"],
  },
  {
    artist: "Worm Shepherd",
    album: "Hunger",
    rank: "15",
    myRate: "92",
    criticsRate: "NR",
    dateRelease: "2024-November-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1077507-hunger_003453.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6ieqQaDcBsbEq569f8wKHl?si=FdA6-r7qR1SE26eItiPZdA",
    genres: ["Deathcore", "Blackened Death Metal", "Symphonic Black Metal"],
  },
  {
    artist: "Psychonaut 4",
    album: "…Of Mourning",
    rank: "16",
    myRate: "92",
    criticsRate: "NR",
    dateRelease: "2024-October-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1051676-of-mourning_020923.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5SCmr0N6XlXf3s7cohLt4k?si=cLwcT3v-QXuiNExeOngwpg",
    genres: ["DSBM", "Black Metal", "Atmospheric Black Metal"],
  },
  {
    artist: "Ihsahn",
    album: "IHSAHN",
    rank: "17",
    myRate: "92",
    criticsRate: "85",
    dateRelease: "2024-February-16",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/797214-ihsahn_130727.jpg",
    spotifyLink: "https://open.spotify.com/album/78eWgdCbll6LBKZR696IBE",
    genres: [
      "Symphonic Metal",
      "Black Metal",
      "Symphonic Black Metal",
      "Progressive Metal",
    ],
  },
  {
    artist: "Immortal Disfigurement",
    album: "KING",
    rank: "18",
    myRate: "92",
    criticsRate: "NR",
    dateRelease: "2024-June-7",
    cover: "https://cdn2.albumoftheyear.org/375x/album/979592-king_181006.jpg",
    spotifyLink:
      "https://open.spotify.com/album/2aHlXLfPMPWlGr248ZeR7E?si=BKPlLW0ZRxW-u3ciH8zQ2Q",
    genres: ["Deathcore", "Symphonic Metal"],
  },
  {
    artist: "Counterparts",
    album: "Heaven Let Them Die",
    rank: "19",
    myRate: "91",
    criticsRate: "84",
    dateRelease: "2024-November-7",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1125106-heaven-let-them-die_151041.jpg",
    spotifyLink: "https://open.spotify.com/album/5pdSJTWNlQj6RJbYPgTFGZ",
    genres: ["Metalcore", "Deathcore"],
  },
  {
    artist: "156/Silence",
    album: "People Watching",
    rank: "20",
    myRate: "91",
    criticsRate: "81",
    dateRelease: "2024-september-13",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1013966-people-watching_143538.jpg",
    spotifyLink: "https://open.spotify.com/album/1PRvYCv9h0rlR4AP54yOnN",
    genres: ["Deathcore", "Metalcore", "Post-Hardcore"],
  },
  {
    artist: "Distant",
    album: "Tsukuyomi: The Origin",
    rank: "21",
    myRate: "91",
    criticsRate: "85",
    dateRelease: "2024-november-22",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1067927-tsukuyomi-the-origin_151014.jpg",
    spotifyLink: "https://open.spotify.com/album/0EZiuTBQrIrbItsLBwkjUk",
    genres: ["Deathcore"],
  },
  {
    artist: "Saidan",
    album: "Visual Kill: The Blossoming of Psychotic Depravity",
    rank: "22",
    myRate: "91",
    criticsRate: "92",
    dateRelease: "2024-may-24",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/931268-visual-kill-the-blossoming-of-psychotic-depravity_174453.jpg",
    spotifyLink: "https://open.spotify.com/album/3GRCZH5yCGXRftwsYOhR5y",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Mister Sister Fister & Infant Annihilator",
    album: "Mister Sister Fister: Re Conception",
    rank: "23",
    myRate: "90",
    criticsRate: "NR",
    dateRelease: "2024-october-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1103070-mister-sister-fister-re-conception_200330.jpg",
    spotifyLink:
      "https://open.spotify.com/album/2pdbIE7lO5QMb2dDh0tKRZ?si=Dkssoz3TR8W9eZ4Xy_05NQ",
    genres: ["Deathcore"],
  },
  {
    artist: "Mitochondrion",
    album: "Vitriseptome",
    rank: "24",
    myRate: "90",
    criticsRate: "80",
    dateRelease: "2024-november-1",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1100899-vitriseptome_073040.jpg",
    spotifyLink: "https://open.spotify.com/album/1PRvYCv9h0rlR4AP54yOnN",
    genres: ["Blackened Death Metal"],
  },
  {
    artist: "Swallow The Sun",
    album: "Shining",
    rank: "25",
    myRate: "90",
    criticsRate: "76",
    dateRelease: "2024-october-18",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1042431-shining_190541.jpg",
    spotifyLink: "https://open.spotify.com/album/1Bk8bpwSWIXDRCJpzEQyPH",
    genres: ["Doom Metal"],
  },
  {
    artist: "Bonecarver",
    album: "Unholy Dissolution",
    rank: "26",
    myRate: "90",
    criticsRate: "NR",
    dateRelease: "2024-may-31",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/934681-unholy-dissolution_133934.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6mXbBnsjq2mNPO10t9IAPp?si=Gk0DkhDsRECmZBrCOhKWuQ",
    genres: ["Deathcore"],
  },
  {
    artist: "Ingested",
    album: "The Tide of Death and Fractured Dreams",
    rank: "27",
    myRate: "89",
    criticsRate: "73",
    dateRelease: "2024-april-5",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/849419-the-tide-of-death-and-fractured-dreams_000218.jpg",
    spotifyLink: "https://open.spotify.com/album/1vrBZpr5a4DEPJNMnpzPkM",
    genres: ["Brutal Death Metal"],
  },
  {
    artist: "Yoth Iria",
    album: "Blazing Inferno",
    rank: "28",
    myRate: "89",
    criticsRate: "80",
    dateRelease: "2024-november-8",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1056019-blazing-inferno_173142.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4GBII1a9TYygGS6FYE5FnJ?si=HnvJzIYbSJW28zRjXBDbtg",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Summoning The Lich",
    album: "Under the Reviled Throne",
    rank: "29",
    myRate: "89",
    criticsRate: "73",
    dateRelease: "2024-july-26",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/958000-under-the-reviled-throne_023156.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5tSuVWooK3ZtbWRBz7pJ0p?si=Eu7wMG7XRHalu6lVwylf7g",
    genres: ["Deathcore"],
  },
  {
    artist: "Chat Pile",
    album: "Cool World",
    rank: "30",
    myRate: "88",
    criticsRate: "83",
    dateRelease: "2024-october-11",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1015369-cool-world_221925.jpg",
    spotifyLink: "https://open.spotify.com/album/3k7GhMNdQ0KXGkC84qVRf2",
    genres: ["Noise Rock"],
  },
  {
    artist: "Darko",
    album: "Starfire",
    rank: "31",
    myRate: "88",
    criticsRate: "76",
    dateRelease: "2024-june-5",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/957709-starfire_173905.jpg",
    spotifyLink: "https://open.spotify.com/album/3IXsOde67YmhbBbt4Vknv0",
    genres: ["Deathcore"],
  },
  {
    artist: "Nocturnal Depression",
    album: "Perpétuelle Eclipse",
    rank: "32",
    myRate: "88",
    criticsRate: "NR",
    dateRelease: "2024-september-26",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1085837-perpetuelle-eclipse_145429.jpg",
    spotifyLink:
      "https://open.spotify.com/album/1HyIneYUXvJ5jtzPXsYsHf?si=-C4MDjW4SaKXcuY4nYr9Mg",
    genres: ["DSBM"],
  },
  {
    artist: "Entheos",
    album: "An End To Everything",
    rank: "33",
    myRate: "87",
    criticsRate: "77",
    dateRelease: "2024-october-25",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1013550-an-end-to-everything_055503.jpg",
    spotifyLink: "https://open.spotify.com/album/4v2BDAKl8BuCw8v2wdJRmz",
    genres: ["Progressive Death Metal"],
  },
  {
    artist: "Oranssi Pazuzu",
    album: "Muuntautuja",
    rank: "34",
    myRate: "87",
    criticsRate: "78",
    dateRelease: "2024-october-11",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1033199-muuntautuja_034914.jpg",
    spotifyLink: "https://open.spotify.com/album/6cRCD79pIJvu5aeKWVtskd",
    genres: ["Avant-Garde Metal"],
  },
  {
    artist: "Dwarrowdelf",
    album: "The Fallen Leaves",
    rank: "35",
    myRate: "87",
    criticsRate: "90",
    dateRelease: "2024-february-2",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/863081-the-fallen-leaves_074649.jpg",
    spotifyLink:
      "https://open.spotify.com/album/7qx5FvIWedRIWAJkRpq5Hu?si=dyNIh8GoRsGnq_sI7j3Cag",
    genres: ["Atmospheric Black Metal"],
  },
  {
    artist: "Unhallowed Deliverance",
    album: "Of Spectres and Strife",
    rank: "36",
    myRate: "87",
    criticsRate: "NR",
    dateRelease: "2024-May-10",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/957588-of-spectres-and-strife_143757.jpg",
    spotifyLink:
      "https://open.spotify.com/album/6lmkK5tz3YUwQIATsSW9Ml?si=sgxPP_H5SoyNm6eFAi1m-g",
    genres: ["Technical Death Metal"],
  },
  {
    artist: "Allt",
    album: "From The New World",
    rank: "37",
    myRate: "87",
    criticsRate: "82",
    dateRelease: "2024-october-4",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1028066-from-the-new-world_205336.jpg",
    spotifyLink: "https://open.spotify.com/album/2sdKwkwaVrSlhKdTuAf2SC",
    genres: ["Metalcore"],
  },
  {
    artist: "Sylosis",
    album: "The Path",
    rank: "38",
    myRate: "86",
    criticsRate: "NR",
    dateRelease: "2024-October-3",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1091712-the-path_210133.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4iZM0ieSYmfdxaPrKceTu5?si=bKIfH24lQYaqmEjQiirUXw",
    genres: ["Melodic Death Metal"],
  },
  {
    artist: "Boundaries",
    album: "Death Is Little More",
    rank: "39",
    myRate: "86",
    criticsRate: "86",
    dateRelease: "2024-March-29",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/864209-death-is-little-more_144231.jpg",
    spotifyLink: "https://open.spotify.com/album/3tyx4wUPmjmHcJHS1jb4eQ",
    genres: ["Metalcore"],
  },
  {
    artist: "Hiraes",
    album: "Dormant",
    rank: "40",
    myRate: "86",
    criticsRate: "60",
    dateRelease: "2024-january-2",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/849793-dormant_120622.jpg",
    spotifyLink:
      "https://open.spotify.com/album/7HYBfqEXZfP4JYfJcrHckC?si=owEV5Le4Q4mKV4prSgAV6Q",
    genres: ["Melodic Death Metal"],
  },
  {
    artist: "Morokh",
    album: "X",
    rank: "41",
    myRate: "86",
    criticsRate: "NR",
    dateRelease: "2024-november-1",
    cover: "https://cdn2.albumoftheyear.org/375x/album/1118815-x_211617.jpg",
    spotifyLink:
      "https://open.spotify.com/album/5ijgDtPKlu1NUDEaADPvzl?si=qYAAoc1FTAWmUR9-OZOwKQ",
    genres: ["Blackened Sludge Metal"],
  },
  {
    artist: "Imminence",
    album: "The Black",
    rank: "42",
    myRate: "86",
    criticsRate: "80",
    dateRelease: "2024-April-12",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/884489-the-black_215209.jpg",
    spotifyLink: "https://open.spotify.com/album/7DYQgveBQDY1xyj4XJ3zzY",
    genres: ["Metalcore"],
  },
  {
    artist: "Borknagar",
    album: "Fall",
    rank: "43",
    myRate: "85",
    criticsRate: "84",
    dateRelease: "2024-february-23",
    cover: "https://cdn2.albumoftheyear.org/375x/album/864127-fall_130632.jpg",
    spotifyLink: "https://open.spotify.com/album/5nK2siMASeGKxTsX9GqY3v",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "Necrophobic",
    album: "In the Twilight Grey",
    rank: "44",
    myRate: "85",
    criticsRate: "84",
    dateRelease: "2024-March-15",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/885702-in-the-twilight-grey_182524.jpg",
    spotifyLink: "https://open.spotify.com/album/2EtaPsV5q2n21XiyF8UclQ",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "In Vain",
    album: "Solemn",
    rank: "45",
    myRate: "84",
    criticsRate: "85",
    dateRelease: "2024-april-19",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/915476-solemn_143731.jpg",
    spotifyLink: "https://open.spotify.com/album/7Kabp5ZGmmD9rF66vpdJs8",
    genres: ["Melodic Death Metal"],
  },
  {
    artist: "Kalandra",
    album: "A Frame Of Mind",
    rank: "46",
    myRate: "84",
    criticsRate: "90",
    dateRelease: "2024-September-13",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/999791-a-frame-of-mind_191204.jpg",
    spotifyLink: "https://open.spotify.com/album/7tmd1LZ4ZT9eoA4Jl1MNFy",
    genres: ["Folk Rock"],
  },
  {
    artist: "Groza",
    album: "Nadir",
    rank: "47",
    myRate: "84",
    criticsRate: "NR",
    dateRelease: "2024-September-20",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1000482-nadir_064657.jpg",
    spotifyLink:
      "https://open.spotify.com/album/4RVc6bTkh9SvjeV89Fsep4?si=Q8wj_ed7S0qvbWIQb-hgZA",
    genres: ["Atmospheric Black Metal"],
  },
  {
    artist: "Spectral Wound",
    album: "Songs of Blood and Mire",
    rank: "48",
    myRate: "83",
    criticsRate: "80",
    dateRelease: "2024-august-23",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/915476-solemn_143731.jpg",
    spotifyLink: "https://open.spotify.com/album/2AljWxmNh0mQPFAKAwKlIt",
    genres: ["Melodic Black Metal"],
  },
  {
    artist: "State Faults",
    album: "Children Of The Moon",
    rank: "49",
    myRate: "83",
    criticsRate: "NR",
    dateRelease: "2024-July-26",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/964459-children-of-the-moon_163258.jpg",
    spotifyLink: "https://open.spotify.com/album/7tqqBxs66oVjVvz7a9Isg7",
    genres: ["Post-Hardcore"],
  },
  {
    artist: "As I Lay Dying",
    album: "The Void Within",
    rank: "50",
    myRate: "83",
    criticsRate: "NR",
    dateRelease: "2024-October-13",
    cover:
      "https://cdn2.albumoftheyear.org/375x/album/1131797-the-void-within_131130.jpg",
    spotifyLink:
      "https://open.spotify.com/album/25a3xkHUh4myBSbuWldXZc?si=lRwOrDzuSi-43tNw0_88iA",
    genres: ["Melodic Death Metal"],
  },
];
